# Generated by Django 3.2.3 on 2021-05-18 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingerdients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(1, 'Liquid'), (2, 'Solid')])),
            ],
            options={
                'db_table': 'ingredients',
            },
        ),
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_password', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'machines',
            },
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=255)),
                ('conventer', models.FloatField()),
            ],
            options={
                'db_table': 'units',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_convert_to_user_unit', models.BooleanField(default=False)),
                ('default_convert_to_user_unit_on_save', models.BooleanField(default=False)),
                ('liquid_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquid_unit', to='main_app.units')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('weight_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weight_unit', to='main_app.units')),
            ],
            options={
                'db_table': 'user_settings',
            },
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modification', models.DateTimeField(auto_now_add=True)),
                ('descripction', models.CharField(default=None, max_length=511)),
                ('recipe_name', models.CharField(max_length=255)),
                ('overall_upvotes', models.IntegerField(default=0)),
                ('last_month_upvotes', models.IntegerField(default=0)),
                ('is_public', models.BooleanField(default=False)),
                ('brewing_temperatue', models.FloatField()),
                ('brewing_time', models.FloatField()),
                ('mixing_time', models.FloatField()),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recipes',
            },
        ),
        migrations.CreateModel(
            name='MachinesStores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.FloatField()),
                ('current_ammount', models.FloatField()),
                ('ingredient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.ingerdients')),
                ('machinie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.machines')),
            ],
            options={
                'db_table': 'machines_stores',
            },
        ),
        migrations.CreateModel(
            name='IngredientsRecipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount_in_default_unit', models.FloatField()),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.recipes')),
                ('unit_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.units')),
            ],
            options={
                'db_table': 'ingredients_recipes',
            },
        ),
        migrations.CreateModel(
            name='FavoriteRecipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.recipes')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favorite_recipes',
            },
        ),
    ]
