# Generated by Django 3.2.3 on 2021-05-18 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoriterecipes',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='favoriterecipes',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='ingredientsrecipes',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='ingredientsrecipes',
            old_name='unit_id',
            new_name='unit',
        ),
        migrations.RenameField(
            model_name='machines',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='machinesstores',
            old_name='ingredient_id',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='machinesstores',
            old_name='machinie_id',
            new_name='machinie',
        ),
        migrations.RenameField(
            model_name='recipes',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='usersettings',
            old_name='user_id',
            new_name='user',
        ),
    ]
