# Generated by Django 3.2.1 on 2021-05-27 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210526_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineContainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.ingerdients')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.machines')),
            ],
            options={
                'db_table': 'machine_container',
            },
        ),
    ]
