# Generated by Django 3.2.3 on 2021-06-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_machinecontainers'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
