# Generated by Django 3.2.3 on 2021-06-01 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_recipes_is_favourite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipes',
            options={'ordering': ('recipe_name',)},
        ),
    ]
