# Generated by Django 3.2.3 on 2021-06-01 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_recipes_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipes',
            options={'ordering': ('is_favourite', 'recipe_name')},
        ),
    ]
