# Generated by Django 3.2.3 on 2021-06-02 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20210602_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='tea_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.teas'),
            preserve_default=False,
        ),
    ]
