# Generated by Django 3.2.1 on 2021-06-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_recipes_tea_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='description',
            field=models.CharField(default='Brak opisu', max_length=1000),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='name',
            field=models.CharField(default='Jan', max_length=255),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='surname',
            field=models.CharField(default='Kowalski', max_length=255),
        ),
    ]
