# Generated by Django 3.2.3 on 2021-06-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_recipes_tea_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='tea_ammount',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
