# Generated by Django 3.2.3 on 2021-06-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_recipes_tea_ammount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='descripction',
            field=models.CharField(default='', max_length=1023),
        ),
    ]
