# Generated by Django 3.2.4 on 2021-06-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_history_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='was_edited',
            field=models.BooleanField(default=False),
        ),
    ]
