# Generated by Django 3.2.4 on 2021-06-07 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_recipes_was_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='was_edited',
        ),
    ]
