# Generated by Django 3.2.5 on 2021-07-13 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20210613_1748'),
        ('main_app', '0017_remove_recipes_was_edited'),
    ]

    operations = [
    ]
